In [1]:
import numpy as np
import pyvista as pv

## Rotation Function

In [2]:
def rotate_points(points, theta, phi, alpha):
    # Create rotation matrix for rotation around z-axis
    Rz = np.array([
        [np.cos(theta), -np.sin(theta), 0],
        [np.sin(theta), np.cos(theta), 0],
        [0, 0, 1]
    ])
    
    # Create rotation matrix for rotation around y-axis
    Ry = np.array([
        [np.cos(phi), 0, np.sin(phi)],
        [0, 1, 0],
        [-np.sin(phi), 0, np.cos(phi)]
    ])
    
    # Create rotation matrix for rotation around x-axis
    Rx = np.array([
        [1, 0, 0],
        [0, np.cos(alpha), -np.sin(alpha)],
        [0, np.sin(alpha), np.cos(alpha)]
    ])
    
    # Combine the rotations (Here @ is matrix multiplication)
    R = Rz @ Ry @ Rx

    # Apply the rotation matrix to each point (R.T is the transpose of R)
    rotated_points = points @ R.T
    
    return rotated_points

https://en.wikipedia.org/wiki/Active_and_passive_transformation#Passive_transformation
For details on why we use Transpose=Inverse.

## Circle on XY Plane

In [3]:
def generate_circle_points(n, radius=1.0):
    # Evenly spaced values over the interval 0,2pi. 
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    # Makes the 3D array
    points = np.column_stack((radius * np.cos(angles), radius * np.sin(angles), np.zeros(n)))
    return points

We should aim for n=4x to have the axes and antipodals. To that end, the user will input a number x, instead of n.

In [4]:
x = 10
n = 4 * x
# Generate circle points
circle_points = generate_circle_points(n)

## Rotate Circle

Low number of points in original circle and high number of rotations will give concentric circles.

In [5]:
# Number of rotations
n_rotations = 5
angles = np.linspace(0, np.pi, n_rotations, endpoint=False)  # Uniformly spaced angles

sphere_points = []

for phi in angles:
    rotated_circle = rotate_points(circle_points, 0, phi, 0)  # Rotate around y-axis
    sphere_points.append(rotated_circle)

sphere_points = np.vstack(sphere_points)

## Small Optimization

In [6]:
threshold = 0.0000001

# Set entries to zero where absolute value is less than the threshold
sphere_points[np.abs(sphere_points) < threshold] = 0

# Remove duplicate points
sphere_points = np.unique(sphere_points, axis=0)

In [8]:
print(sphere_points)

[[-1.          0.          0.        ]
 [-0.98768834 -0.15643447  0.        ]
 [-0.98768834  0.15643447  0.        ]
 [-0.95105652 -0.30901699  0.        ]
 [-0.95105652  0.30901699  0.        ]
 [-0.89100652 -0.4539905   0.        ]
 [-0.89100652  0.4539905   0.        ]
 [-0.80901699 -0.58778525  0.        ]
 [-0.80901699  0.          0.58778525]
 [-0.80901699  0.         -0.58778525]
 [-0.80901699  0.58778525  0.        ]
 [-0.79905665 -0.15643447  0.58054864]
 [-0.79905665  0.15643447 -0.58054864]
 [-0.79905665  0.15643447  0.58054864]
 [-0.79905665 -0.15643447 -0.58054864]
 [-0.76942088 -0.30901699  0.55901699]
 [-0.76942088  0.30901699  0.55901699]
 [-0.76942088 -0.30901699 -0.55901699]
 [-0.76942088  0.30901699 -0.55901699]
 [-0.72083942 -0.4539905   0.52372049]
 [-0.72083942  0.4539905  -0.52372049]
 [-0.72083942  0.4539905   0.52372049]
 [-0.72083942 -0.4539905  -0.52372049]
 [-0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [-0.6545085  -0.58778525

## Visualization

In [7]:
# Visualize using PyVista
plotter = pv.Plotter()
plotter.add_points(sphere_points, color='blue', point_size=5)
plotter.show_grid()
plotter.show()

Widget(value='<iframe src="http://localhost:64514/index.html?ui=P_0x15aaa0d30_0&reconnect=auto" class="pyvista…