### Radians

In [10]:
import numpy as np
import pyvista as pv

# Prompt the user for the number of points
N = int(input("Enter the number of points: "))

# Initialize lists to store angles
angles = []

# Collect N pairs of rational angles from the user and multiply by pi
for i in range(N):
    theta_ratio = float(input(f"Enter rational number for angle theta (will be multiplied by pi) for point {i+1}: "))
    phi_ratio = float(input(f"Enter rational number for angle phi (will be multiplied by pi) for point {i+1}: "))
    theta = theta_ratio * np.pi
    phi = phi_ratio * np.pi
    angles.append((theta, phi))

# Convert spherical coordinates to Cartesian coordinates
points = [(np.sin(phi) * np.cos(theta), np.sin(phi) * np.sin(theta), np.cos(phi)) for theta, phi in angles]

# Convert points to a numpy array
points = np.array(points)
print(points)

# Visualize using PyVista
plotter = pv.Plotter()
plotter.add_points(points, color='blue', point_size=10)
plotter.show_grid()
plotter.show()

Enter the number of points:  4
Enter rational number for angle theta (will be multiplied by pi) for point 1:  1
Enter rational number for angle phi (will be multiplied by pi) for point 1:  2
Enter rational number for angle theta (will be multiplied by pi) for point 2:  1.2
Enter rational number for angle phi (will be multiplied by pi) for point 2:  .3
Enter rational number for angle theta (will be multiplied by pi) for point 3:  2.3
Enter rational number for angle phi (will be multiplied by pi) for point 3:  2
Enter rational number for angle theta (will be multiplied by pi) for point 4:  1.1
Enter rational number for angle phi (will be multiplied by pi) for point 4:  .1


[[ 2.44929360e-16 -2.99951957e-32  1.00000000e+00]
 [-6.54508497e-01 -4.75528258e-01  5.87785252e-01]
 [-1.43965866e-16 -1.98152015e-16  1.00000000e+00]
 [-2.93892626e-01 -9.54915028e-02  9.51056516e-01]]


Widget(value='<iframe src="http://localhost:45843/index.html?ui=P_0x791599179c10_6&reconnect=auto" class="pyvi…

### Degrees

In [13]:
# Prompt the user for the number of points
N = int(input("Enter the number of points: "))

# Initialize lists to store angles
angles = []

# Collect N pairs of angles in degrees from the user
for i in range(N):
    theta_deg = float(input(f"Enter angle theta (in degrees) for point {i+1}: "))
    phi_deg = float(input(f"Enter angle phi (in degrees) for point {i+1}: "))
    theta = np.radians(theta_deg)
    phi = np.radians(phi_deg)
    angles.append((theta, phi))

# Convert spherical coordinates to Cartesian coordinates
points = [(np.sin(phi) * np.cos(theta), np.sin(phi) * np.sin(theta), np.cos(phi)) for theta, phi in angles]

# Convert points to a numpy array
points = np.array(points)
print(points)

# Visualize using PyVista
plotter = pv.Plotter()
plotter.add_points(points, color='blue', point_size=10)
plotter.show_grid()
plotter.show()


Enter the number of points:  5
Enter angle theta (in degrees) for point 1:  20
Enter angle phi (in degrees) for point 1:  20
Enter angle theta (in degrees) for point 2:  45
Enter angle phi (in degrees) for point 2:  45
Enter angle theta (in degrees) for point 3:  23
Enter angle phi (in degrees) for point 3:  23
Enter angle theta (in degrees) for point 4:  43
Enter angle phi (in degrees) for point 4:  43
Enter angle theta (in degrees) for point 5:  23
Enter angle phi (in degrees) for point 5:  23


[[0.3213938  0.11697778 0.93969262]
 [0.5        0.5        0.70710678]
 [0.3596699  0.15267081 0.92050485]
 [0.49878203 0.46512176 0.7313537 ]
 [0.3596699  0.15267081 0.92050485]]


Widget(value='<iframe src="http://localhost:45843/index.html?ui=P_0x79158751bbc0_8&reconnect=auto" class="pyvi…