In [1]:
import persistence_functions as pf
import numpy as np

## We want data as above

### NOTE!
The points and edges need not be ordered by height, that will happen later.

In [2]:
import trimesh
import pyvista as pv

In [3]:
# Load the .obj file
torus_mesh = trimesh.load('../shared/triangulated_torus_2.obj')

In [4]:
# Print basic information about the mesh

torus_vertices = torus_mesh.vertices
torus_edges = torus_mesh.edges_unique
torus_normals = torus_mesh.vertex_normals

direction = [0,0,1]

In [5]:
print(torus_vertices[0])
print(torus_normals)

[ 1.260115 -0.055516 -0.082107]
[[ 0.6828 -0.7293  0.0426]
 [ 0.7347 -0.6712  0.0987]
 [ 0.9218  0.2831 -0.2647]
 ...
 [ 0.9135  0.3443  0.2167]
 [ 0.5652 -0.7288  0.3866]
 [ 0.5643 -0.7305  0.3847]]


In [6]:
def vertex_height_dictionary(vertices, direction):
    height_dictionary = {}
    for index, vertex in enumerate(vertices):
        height_dictionary[index] = pf.height_of_vertex(direction, vertex)
    return height_dictionary

In [7]:
v_h_d = vertex_height_dictionary(torus_vertices, direction)

In [8]:
def format_blender_vertices(vertices, normals, height_dictionary):
    points = []
    vertices = np.array(vertices)
    for index, vertex in enumerate(vertices):
        points.append([vertex, height_dictionary[index], normals[index]])
    return points

In [9]:
b_v = format_blender_vertices(torus_vertices, torus_normals, v_h_d)

In [10]:
print(b_v[0])

[array([ 1.260115, -0.055516, -0.082107]), np.float64(-0.082107), array([ 0.6828, -0.7293,  0.0426])]


In [18]:
def format_blender_edges(edges, height_dictionary):
    edges_list = []
    edges = np.array(edges)
    for index, edge in enumerate(edges):
        print(edge)
        print(edge + 1)
        edges_list.append([edge + 1, height_dictionary[index], [1,0,0]])
    return edges_list

In [19]:
b_e = format_blender_edges(torus_edges, v_h_d)

[ 4 10]
[ 5 11]
[ 2 11]
[ 3 12]
[17 19]
[18 20]
[16 21]
[17 22]
[22 25]
[23 26]
[20 27]
[21 28]
[ 5 30]
[ 6 31]
[ 0 31]
[ 1 32]
[ 7 34]
[ 8 35]
[ 9 36]
[10 37]
[15 37]
[16 38]
[12 38]
[13 39]
[23 43]
[24 44]
[32 47]
[33 48]
[33 49]
[34 50]
[24 50]
[25 51]
[ 3 51]
[ 4 52]
[32 52]
[33 53]
[47 52]
[48 53]
[ 5 54]
[ 6 55]
[30 54]
[31 55]
[48 55]
[49 56]
[ 2 57]
[ 3 58]
[11 57]
[12 58]
[ 9 58]
[10 59]
[36 58]
[37 59]
[56 59]
[57 60]
[ 3 60]
[ 4 61]
[51 60]
[52 61]
[40 61]
[41 62]
[14 63]
[15 64]
[20 64]
[21 65]
[27 64]
[28 65]
[17 65]
[18 66]
[19 65]
[20 66]
[28 66]
[29 67]
[28 67]
[29 68]
[66 67]
[67 68]
[45 69]
[46 70]
[62 70]
[63 71]
[24 72]
[25 73]
[50 72]
[51 73]
[40 73]
[41 74]
[61 73]
[62 74]
[42 74]
[43 75]
[56 77]
[57 78]
[59 77]
[60 78]
[53 79]
[54 80]
[44 80]
[45 81]
[48 81]
[49 82]
[55 81]
[56 82]
[53 82]
[54 83]
[79 82]
[80 83]
[78 84]
[79 85]
[68 85]
[69 86]
[35 87]
[36 88]
[12 88]
[13 89]
[38 88]
[39 89]
[62 90]
[63 91]
[70 90]
[71 91]
[14 91]
[15 92]
[63 91]
[64 92]
[35 93]


## This is where processing ends

In [13]:
formatted_vertices, formatted_edges = pf.format_graph([b_v, b_e])

In [14]:
print(formatted_edges)

[{'vertices': array([ 5, 11]), 'h': np.float64(-0.082107), 'n': [1, 0, 0]}, {'vertices': array([ 3, 12]), 'h': np.float64(-0.082107), 'n': [1, 0, 0]}, {'vertices': array([18, 20]), 'h': np.float64(-0.082107), 'n': [1, 0, 0]}, {'vertices': array([17, 22]), 'h': np.float64(-0.082107), 'n': [1, 0, 0]}, {'vertices': array([23, 26]), 'h': np.float64(-0.082107), 'n': [1, 0, 0]}, {'vertices': array([21, 28]), 'h': np.float64(-0.082107), 'n': [1, 0, 0]}, {'vertices': array([ 6, 31]), 'h': np.float64(-0.060359), 'n': [1, 0, 0]}, {'vertices': array([ 1, 32]), 'h': np.float64(-0.060359), 'n': [1, 0, 0]}, {'vertices': array([ 8, 35]), 'h': np.float64(-0.060359), 'n': [1, 0, 0]}, {'vertices': array([10, 37]), 'h': np.float64(-0.060359), 'n': [1, 0, 0]}, {'vertices': array([16, 38]), 'h': np.float64(-0.060359), 'n': [1, 0, 0]}, {'vertices': array([13, 39]), 'h': np.float64(-0.060359), 'n': [1, 0, 0]}, {'vertices': array([24, 44]), 'h': np.float64(-0.252647), 'n': [1, 0, 0]}, {'vertices': array([33, 

In [15]:
processed_graph = pf.process_graph(formatted_vertices, formatted_edges, direction)

In [16]:
print(processed_graph[1])

[[[26, 97], np.float64(-1.253587), 0], [[41, 109], np.float64(-1.253587), 0], [[47, 107], np.float64(-1.253587), 0], [[74, 96], np.float64(-1.253587), 0], [[77, 108], np.float64(-1.253587), 0], [[80, 107], np.float64(-1.253587), 0], [[2, 25], np.float64(-1.206774), 0], [[8, 24], np.float64(-1.206774), 0], [[24, 34], np.float64(-1.206774), 0], [[28, 30], np.float64(-1.206774), 0], [[62, 91], np.float64(-1.206774), 0], [[6, 23], np.float64(-1.171501), 0], [[11, 23], np.float64(-1.171501), 0], [[15, 46], np.float64(-1.171501), 0], [[44, 102], np.float64(-1.171501), 0], [[46, 86], np.float64(-1.171501), 0], [[47, 80], np.float64(-1.171501), 0], [[6, 11], np.float64(-1.158316), 0], [[73, 78], np.float64(-1.158316), 0], [[79, 101], np.float64(-1.158316), 0], [[79, 111], np.float64(-1.158316), 0], [[81, 104], np.float64(-1.158316), 0], [[13, 66], np.float64(-1.119635), 0], [[35, 67], np.float64(-1.119635), 0], [[40, 66], np.float64(-1.119635), 0], [[43, 65], np.float64(-1.119635), 0], [[45, 1

In [17]:
critical_points = pf.compute_critical_points(processed_graph)
print(critical_points)

([{'point': [1, np.float64(-1.253587), -1]}, {'point': [2, np.float64(-1.253587), -1]}, {'point': [3, np.float64(-1.253587), -1]}, {'point': [4, np.float64(-1.253587), -1]}, {'point': [5, np.float64(-1.253587), -1]}, {'point': [6, np.float64(-1.253587), -1]}, {'point': [7, np.float64(-1.206774), -1]}, {'point': [8, np.float64(-1.206774), -1]}, {'point': [9, np.float64(-1.206774), -1]}, {'point': [10, np.float64(-1.206774), -1]}, {'point': [11, np.float64(-1.206774), -1]}, {'point': [12, np.float64(-1.171501), -1]}, {'point': [13, np.float64(-1.171501), -1]}, {'point': [14, np.float64(-1.171501), -1]}, {'point': [15, np.float64(-1.171501), -1]}, {'point': [16, np.float64(-1.171501), -1]}, {'point': [17, np.float64(-1.171501), -1]}, {'point': [18, np.float64(-1.158316), -1]}, {'point': [19, np.float64(-1.158316), -1]}, {'point': [20, np.float64(-1.158316), -1]}, {'point': [21, np.float64(-1.158316), -1]}, {'point': [22, np.float64(-1.158316), -1]}, {'point': [26, np.float64(-1.119635), -